FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
USER $APP_UID
WORKDIR /app


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["src/Messenger.Migrator/Messenger.Migrator.csproj", "src/Messenger.Migrator/"]
RUN dotnet restore "./src/Messenger.Migrator/Messenger.Migrator.csproj"

COPY . .
WORKDIR "/src/src/Messenger.Migrator"

RUN dotnet build "./Messenger.Migrator.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release

RUN dotnet publish "./Messenger.Migrator.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Messenger.Migrator.dll"]